language: python
env:
  - CODECOV_TOKEN="4762bec3-452b-4e1d-bef3-a55b76460b97"
python:
  - "3.7"
install:
  - pip install .
  - pip install nose codecov
  - pip install 'numpy==1.18.1' --force-reinstall --no-cache-dir
script:
  - pytest --cov=.
after_success:
  - codecov -t $CODECOV_TOKEN
