language: python
env:
  - CODECOV_TOKEN="4762bec3-452b-4e1d-bef3-a55b76460b97"
python:
  - "3.7"
install:
  - pip install .
  - pip install nose pytest-cov
script:
  - pytest --cov=.
after_success:
  - codecov -t $CODECOV_TOKEN

