import libsbml

print("OP SUCCESS: ", libsbml.LIBSBML_OPERATION_SUCCESS)
print("OP FAIL: ", libsbml.LIBSBML_OPERATION_FAILED)
print("INVALID OBJ: ", libsbml.LIBSBML_INVALID_OBJECT)
print("LEVEL MISMATCH: ", libsbml.LIBSBML_LEVEL_MISMATCH)
print("LIBSBML_VERSION_MISMATCH: ", libsbml.LIBSBML_VERSION_MISMATCH) 
print("PKG VERSION MISMATCH: ", libsbml.LIBSBML_PKG_VERSION_MISMATCH)
print("dup obj id: ", libsbml.LIBSBML_DUPLICATE_OBJECT_ID)


print("success ", libsbml.LIBSBML_OPERATION_SUCCESS)
print("index exceeds size ", libsbml.LIBSBML_INDEX_EXCEEDS_SIZE)
print("unexpected attribute ", libsbml.LIBSBML_UNEXPECTED_ATTRIBUTE)
print("operation failed ", libsbml.LIBSBML_OPERATION_FAILED)
print("invalid attribute value ", libsbml.LIBSBML_INVALID_ATTRIBUTE_VALUE)
print("invalid object ", libsbml.LIBSBML_INVALID_OBJECT)
print("duplicate object id ", libsbml.LIBSBML_DUPLICATE_OBJECT_ID)
print("level mismatch ", libsbml.LIBSBML_LEVEL_MISMATCH)
print("version mismatch ", libsbml.LIBSBML_VERSION_MISMATCH)
print("invalid xml operation ", libsbml.LIBSBML_INVALID_XML_OPERATION)
print("namespaces mismatch ", libsbml.LIBSBML_NAMESPACES_MISMATCH)
print("duplicate annotation ns ", libsbml.LIBSBML_DUPLICATE_ANNOTATION_NS)
print("annoation name not found ", libsbml.LIBSBML_ANNOTATION_NAME_NOT_FOUND)
print("annotation ns not found ", libsbml.LIBSBML_ANNOTATION_NS_NOT_FOUND)
print("missing metaid ", libsbml.LIBSBML_MISSING_METAID)
print("deprecated attribute ", libsbml.LIBSBML_DEPRECATED_ATTRIBUTE)
print("use id attribute ", libsbml.LIBSBML_USE_ID_ATTRIBUTE_FUNCTION)
print("pkg version mismatch ", libsbml.LIBSBML_PKG_VERSION_MISMATCH)
print("pkg unknown ", libsbml.LIBSBML_PKG_UNKNOWN)
print("pkg unknown version ", libsbml.LIBSBML_PKG_UNKNOWN_VERSION)
print("pkg disabled ", libsbml.LIBSBML_PKG_DISABLED)
print("pkg conflicted version ", libsbml.LIBSBML_PKG_CONFLICTED_VERSION)
print("pkg conflict ", libsbml.LIBSBML_PKG_CONFLICT)
print("conv invalid target ns ", libsbml.LIBSBML_CONV_INVALID_TARGET_NAMESPACE)
print("conv pkg conversion not available ", libsbml.LIBSBML_CONV_PKG_CONVERSION_NOT_AVAILABLE)
print("conv invalid src doc ", libsbml.LIBSBML_CONV_INVALID_SRC_DOCUMENT)
print("conv conversion not available ", libsbml.LIBSBML_CONV_CONVERSION_NOT_AVAILABLE)
print("conv pkg considered unknown ", libsbml.LIBSBML_CONV_PKG_CONSIDERED_UNKNOWN)