import libsbml

print("OP SUCCESS: ", libsbml.LIBSBML_OPERATION_SUCCESS)
print("OP FAIL: ", libsbml.LIBSBML_OPERATION_FAILED)
print("INVALID OBJ: ", libsbml.LIBSBML_INVALID_OBJECT)
print("LEVEL MISMATCH: ", libsbml.LIBSBML_LEVEL_MISMATCH)
print("LIBSBML_VERSION_MISMATCH: ", libsbml.LIBSBML_VERSION_MISMATCH) 
print("PKG VERSION MISMATCH: ", libsbml.LIBSBML_PKG_VERSION_MISMATCH)
print("dup obj id: ", libsbml.LIBSBML_DUPLICATE_OBJECT_ID)




