/* MIT License
*/

//== FILEDOC =========================================================================

/** @file config.h
 * @brief Autogenerated configure header
  */

//== BEGINNING OF CODE ===============================================================

#ifndef __SAGITTARIUS_CONFIGURE_HEADER__
#define __SAGITTARIUS_CONFIGURE_HEADER__

#define SBNW_MAJOR_VER      1
#define SBNW_MINOR_VER      0
#define SBNW_PATCHLEVEL     0

//#define SAGITTARIUS_BIN_PATH 

#define SBNW_USE_MAGICK     
#define SBNW_DEBUG_LEVEL    

#endif //#ifndef __SAGITTARIUS_CONFIGURE_HEADER__
